### ISSUE TITLE
Earlier deploy

### ISSUE THREAD

**Issue by Berkay-akbas** [Berkay-akbas/Portfolio-Page#8]
I Have deployed my page earlier and this is the link to the page
https://berkay-akbas.github.io/Portfolio-Page/

**Comment by ShadyShawkat** [comment]
## Hi @Berkay-akbas, 

Your project is complete!  There is nothing else to say :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/qlrBlSDevEdFeW5JwV/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
